        
		<footer id="footer">
			<p>
				<a href="index">2014 Annual Report</a> |
				<a href="partner">Partner</a> |
				<a href="contact">Contact</a> | 
				<a href="http://bikeandbuild.org"target=_blank> Bike &amp; Build Home </a>  
			</p>
			
			<p><small>All content © Bike & Build Inc. 2014&ndash;2015</small></p>
		</footer>
		
		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.1.min.js"><\/script>')</script>

        <script src="js/plugins.js"></script>
		
		
		<script src="js/gsap/TweenMax.min.js"> </script>
		<script src="js/gsap/ScrollToPlugin.min.js"> </script>
		<script src="js/gsap/TextPlugin.min.js"> </script>
		<script src="js/jquery.scrollmagic.min.js"></script>
		
		<script src="js/jquery.scrollmagic.debug.js"></script>
		
		<script src="js/anim.js"></script>
		
        <script src="js/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>
