<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Bike &amp; Build | 2014</title>
		<meta name="description" content="A look back at our accomplishments in 2014">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width = device-width, initial-scale=1, maximum-scale=1, user-scalable = no">

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
		<link rel="stylesheet" href="css/custom.css">
	   
	    <script type="text/javascript" src="//use.typekit.net/fkv4vwx.js"></script>
	    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="js/vendor/html5shiv.js"><\/script>')</script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
						
	<header id="header">			
		<div class="" id="toggle-btn">
	        <button type="button" id="toggle" role="button" aria-label="Toggle Navigation" class="lines-button x2">
	          <span id="icon-menu" class="icon-menu">  </span>
			  <span id="icon-cross" class="icon-cross"> </span>
	        </button>
		</div>
		<nav id="toc">		
			<h3> Contents </h3>
			<ol>
				<li> <a class="scrollnav-link" id="link" href="#Intro"> 	
						<span class="toc-name"> Intro </span>	
					</a> 
				</li>
				<li> <a class="scrollnav-link" id="link" href="#Accomplishments">
						<span class="toc-name"> 2014 Accomplishments		</span>	
					</a> 
				</li>
				<li> <a class="scrollnav-link" id="link" href="#BB101"> 	
						<span class="toc-name"> Bike and Build 101	</span>	
					</a> 
				</li>
				<li> <a class="scrollnav-link" id="link" href="#Impact"> 
						<span class="toc-name"> Impact </span>	
					</a> 
				</li>
				<li> <a class="scrollnav-link" id="link" href="#Riders"> 	
						<span class="toc-name"> Riders </span>	
					</a> 
				</li>
				<li> <a class="scrollnav-link" id="link" href="#Alumni"> 	
						<span class="toc-name"> Alumni </span>	
					</a> 
				</li>
				<li> <a class="scrollnav-link" id="link" href="#Financials"> 
						<span class="toc-name"> Statement of Financials </span>	
					</a> 
				</li>
			</ol>
			<ul>
				<li> 
					<a class="scrollnav-link" id="link" href="partner"> 	
						<span class="toc-name"> Partner	</span>	
					</a> 
				</li>
				<li> 
					<a class="scrollnav-link" id="link" href="contact"> 	
						<span class="toc-name"> Contact </span>	
					</a> 
				</li>
				<li>
					<a href="http://bikeandbuild.org"target=_blank> Bike and Build Home <span class="icon-open"> </span> </a>
				</li>
			</ul>
		</nav>

	</header>